version: "3.8"

services:
  gpt-bot:
    container_name: gpt-bot
    build:
      context: . 
      dockerfile: Dockerfile
    restart: always
    environment:
      - TELEGRAM_API_KEY=
      - OPENAI_API_KEY=
      - PASSWD=
      - BOTADMIN=
    volumes:
      - user-data:/app/data
volumes:
  user-data: